default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: Pk@7470588990

development:
  <<: *default
  database: helloworld
  username: postgres
  password: Pk@7470588990

test:
  <<: *default
  database: helloworld

production:
  <<: *default
  database: helloworld
  username: postgres
  password: Pk@7470588990
