default: &default
  adapter: mysql
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 7470588990
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: helloworld

test:
  <<: *default
  database: helloworld

production:
  url: <%= ENV['DATABASE_URL'] %>

