default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: 7470588990
  host: localhost
  

development:
  <<: *default
  database: helloworld

test:
  <<: *default
  database: helloworld

production:
   <<: *default
   database: helloworld
